### PR TITLE
Code refactory, React Hooks Integration, New Filling Color Algorithm and Customizable Colors

### PR DESCRIPTION
**Pull request by kuraydev**
Hello @ayooby,
I love the idea of the library :) 
I simply re-written some parts of the library and refactored lots of stuff. 

# What is done?
- New Util JS to take apart a lot of code from main part.
- New Color Algorithm (Old ones not working, just colourized black because of the algorithm was wrong)
- New React Hooks Integration
- Now, colours are customizable
- Example folder is added with a working one
- Re-written the README

I also would like to be an **active maintainer** of this project :) 
Thank you again.

### CODE REVIEW

**Comment by ayooby** [comment]
Hello @WrathChaos,

I'm glad that you liked the repo, please let me check the PR.
I guess there is no issue with being an Active Maintainer and I would be happy to have you.

**Review by ayooby — APPROVED** [review]

**Comment by sgup** [comment]
Can you put this latest on NPM?

**Comment by kuraydev** [comment]
@ayooby We need you sir :)

**Comment by ayooby** [comment]
@WrathChaos I'm on it.

**Comment by sgup** [comment]
Thanks @ayooby! Could you maybe remove the console log?
image

I'll make a PR for this repo soon, love the project + would be nice to have some more options!

**Comment by kuraydev** [comment]
> Thanks @ayooby! Could you maybe remove the console log?
> image
> 
> I'll make a PR for this repo soon, love the project + would be nice to have some more options!

Waiting for it :) I guess I forgot to remove those console.logs 😭 Oops, sorry

**Comment by cyclops24** [comment]
@WrathChaos I love your refactoring and new version. Please apply this also on main React repo: https://github.com/kevinsqi/react-calendar-heatmap
I think this refactoring can be very useful as a next step for React version too.

**Comment by kuraydev** [comment]
@cyclops24 Does not it React only? How should I apply this on that repo?

**Pull request merged**
